apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Teeworks1/SC-chart.git
    #targetRevision: HEAD
    targetRevision: master
    path: sc-chart
    helm:
      releaseName: SC-chart
      valueFiles:
       - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    retry:
      limit: 2
